### ISSUE TITLE
MirrorVertexGroups keeps return DictGroup error custom pattern

### ISSUE THREAD

**Issue by schroef** [spiraloid/Spiraloid-Toolkit-for-Blender#3]
MirrorVertexGroups 0.0.1
OSX 10.11.6
bl 2.83

Im using trying to use the mirror action using a custom pattern to limit the number of groups it will mirror. Im using this pattern "LeftLegUp" + "RightLegUp", im not sure the enum pattern then will also be used, its not being grayed out as you choose custom.

Each time i tried it, it loops over all existing groups, then when it reaches that group return a dictgroup error.

Here's short past of the console, it has a long list of each group, but thats not needed for this error
```
ixamorig:LeftFoot
318
mixamorig:LeftToeBase
318
mixamorig:LeftFoot
320
mixamorig:RightFoot
320
mixamorig:LeftLeg
320
mixamorig:LeftToeBase
320
mixamorig:LeftFoot
319
mixamorig:LeftLeg
319
mixamorig:LeftToeBase
319
mixamorig:LeftLeg
317
mixamorig:RightFoot
317
mixamorig:LeftToeBase
317
mixamorig:LeftLeg
318
mixamorig:Spine2
318
mixamorig:LeftToeBase
318
mixamorig:LeftLeg
317
Traceback (most recent call last):
  File "/Users/macpro1/Library/Application Support/Blender/2.80/scripts/addons/MirrorAllVertexGroups.py", line 206, in execute
    copy_mirror_weight(self.enum_Axis,self.enum_Way,self.enum_Pattern,self.special_pattern,self.left_side,self.right_side,self.tolerance)
  File "/Users/macpro1/Library/Application Support/Blender/2.80/scripts/addons/MirrorAllVertexGroups.py", line 162, in copy_mirror_weight
    print(DictGroup[group.group])
KeyError: 60

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/Users/macpro1/Library/Application Support/Blender/2.80/scripts/addons/MirrorAllVertexGroups.py", line 206, in execute
    copy_mirror_weight(self.enum_Axis,self.enum_Way,self.enum_Pattern,self.special_pattern,self.left_side,self.right_side,self.tolerance)
  File "/Users/macpro1/Library/Application Support/Blender/2.80/scripts/addons/MirrorAllVertexGroups.py", line 162, in copy_mirror_weight
    print(DictGroup[group.group])
KeyError: 60

location: <unknown location>:-1
```

That KeyError seems to be different each time i run it.

**Comment by schroef** [comment]
PS in the top it says "Actions", that is some leftover code i guess, i see in the code its just a string and has not functionality

![popup-mirrorvertexgroups](https://user-images.githubusercontent.com/6923008/127366239-92945565-e9a4-4200-a7f0-161818a05cda.png)

**Comment by schroef** [comment]
Does the custom pattern only look at trailing pattern. so everything after the dot?
Im testing this on a Mixamo rig and it doesnt have the regular pattern like .l or .r or any of these it has Left and Right in the middle of the name.

If i understand the error correct, it looks like it cant find the pattern. Im not sure also why it states the same group multiple times. For instance the group "mixamo:head" is shown 146 times in the output, seems like its running over code again and again adding to a dictgroup but that cause it to get added multiple times.

Ive added the complete output here in a log file
[error-custom-pattern.log](https://github.com/spiraloid/Spiraloid-Toolkit-for-Blender/files/6895281/error-custom-pattern.log)

The error is there because is no error catch as well.

After trying a simpler pattern with just the word 'Left' and 'Right', i did run, yet im not sure if the outcome is correct. It basically made left and right the same. I thought it would mirror from L to R and use propernaming.

I do notice when i add say :LeftLegUp as a custom pattern, then it seems to go wack. It then basically mirrors from left to right in the left group and the right group is basically empty.
![custom-pattern-issue](https://user-images.githubusercontent.com/6923008/127372298-f54530ac-d9f0-4c11-a098-697006815e64.png)

PS i altered the operator, so now when it has an error it will show that in the bottom info panel, it will also show when its done. At the end i tried showing the issue i pasted earlier, when i use a pattern which also adds something else other then Left or Right
![operator-feedback](https://user-images.githubusercontent.com/6923008/127372812-9a0ce818-080c-4481-807a-0cf89b9121e8.gif)

**Comment by schroef** [comment]
I believe the issue here is how it is applying vertex groups when using a custom pattern. I think it will always try to delete and add no matter the pattern. I see a couple for loops and in one i do see the pattern is being search for. But in the loop below that it is not, i think thats causing the issue here.

When i use a pattern of only "left" en "right" it does work, when i expand it to say "LeftUp" to narrow the results down it causes an error. I think thats to those second for loops deleting and adding no matter if the pattern is in there.

**Comment by spiraloid** [comment]
hey sorry I just saw this.  yeah the code is using a trailing pattern.   the _L and _R are best as other tools don't like "." in object names.    you can use the batch rename tool in the menu to conform badly named skeletons btw.

**Comment by spiraloid** [comment]
I found this code and ported it since I use it a lot.  I am draconian about skeleton naming so if you are trying to use it on a messy skeleton naming it's going to be easy to break.  I suggest renaming your skeletons to follow a clean standard and use "_L" and "_R" suffixes for chirality.    the batch rename tool is your friend here.

![image](https://user-images.githubusercontent.com/36362743/162614237-52cd5419-26a1-42ea-92b8-24f21c7ac596.png)
