### ISSUE TITLE
MirrorVertexGroup 2.93 broken

### ISSUE THREAD

**Issue by negativecitizen** [spiraloid/Spiraloid-Toolkit-for-Blender#4]
Regards. Seems that the changes introduced in python 2.93 braked the MirrorAllVertex Group  :( 
https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API
![Screen Shot 10-3-2021 at 1 56 AM](https://user-images.githubusercontent.com/69877435/135743519-a53b3566-144f-4932-8d6c-00048aa8f842.png)
PI

**Comment by spiraloid** [comment]
should be fixed in 3.1 update
