### ISSUE TITLE
strange error when try click "new 3d comic" 

### ISSUE THREAD

**Issue by umotivo-official** [spiraloid/Spiraloid-Toolkit-for-Blender#6]
Hi,

I got this error when try create new:

Python: Traceback (most recent call last):
  File "C:\---------------\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Spiraloid-Toolkit-for-Blender-3DComicToolkit-master\3DComicToolkit.py", line 3646, in execute
    scripts_dir = bpy.utils.user_resource('SCRIPTS', "addons")
TypeError: user_resource() takes 1 positional argument but 2 were given

location: <unknown location>:-1

please help

**Comment by spiraloid** [comment]
I have a new version coming for 3.2 with the error fixed. (is about the resources folder not being set in preferences.)
